version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-04-01 to 2021-09-30 by month" --output-dir=output --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz
        #This has been taken from https://github.com/opensafely/sro-template/blob/master/project.yaml
        #The output files are not there, but assume it will give the 30 input files witht the suffices being the months
        #The .gz extension code above is to turn it into a compressed file


  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
      #Give errors if used: --index-date-range "2019-04-01 to 2021-09-30 by month" --output-format csv
      needs: [generate_study_population]
      outputs:
        moderately_sensitive:
          measure_csv: output/measure_*.csv


  # run_model:
  #   run: python:analysis/PSA_graphs.py
  #   needs: [generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       measure_csv: output/PSA_test_total_table.csv
  
  #Code below functioning as of 2021 10 27
  #New 2021/10/11 - PSA_graphs.py working in ypnb book locally, but gives error whem running model
  run_model:
    #python:latest is in principle needed. All slashes in paths should be forward slashes
    run: python:latest python analysis/PSA_graphs.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        plots: output/*.jpg #Tests_long_list.jpg, output/Tests_short_list.jpg - comma to separate lists may not work
        #Putting a second line with plots and a different output gives duplicate key error
